name: furniture_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  flutter_riverpod: ^2.1.1
  firebase_analytics: ^10.0.7
  uuid: ^3.0.7
  firebase_messaging: ^14.2.1
  overlay_support: ^2.1.0
  http: ^0.13.5
  persistent_bottom_nav_bar_v2: ^4.2.6
  go_router: ^6.0.4
  map_location_picker: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

    # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  