// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYw1Jxnsvd-YsfFRrOgh6VpuFCXzasy08',
    appId: '1:4699676537:web:1a9b7449150f4d58b659a8',
    messagingSenderId: '4699676537',
    projectId: 'furniture-shop-4c88a',
    authDomain: 'furniture-shop-4c88a.firebaseapp.com',
    storageBucket: 'furniture-shop-4c88a.appspot.com',
    measurementId: 'G-N64J5F9R59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFJDUZfu86fp5DZNAKZ3TVJhjDFczh0E',
    appId: '1:4699676537:android:340a9894f0cf9ccab659a8',
    messagingSenderId: '4699676537',
    projectId: 'furniture-shop-4c88a',
    storageBucket: 'furniture-shop-4c88a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSEzmjCSLvW7w9_uPEeWmbV0NjD-YXMs',
    appId: '1:4699676537:ios:3c89513c6ea7c5b3b659a8',
    messagingSenderId: '4699676537',
    projectId: 'furniture-shop-4c88a',
    storageBucket: 'furniture-shop-4c88a.appspot.com',
    iosClientId: '4699676537-ou9kqjqbfofchajnd55nc3k04c3a4h7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureShop',
  );
}
