// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaz959ZNqBGMiPZ1rjgjAqX3mGeNIxsc',
    appId: '1:597603192637:web:fe0e4aaa4ba2af4000bf54',
    messagingSenderId: '597603192637',
    projectId: 'furniture-shopy',
    authDomain: 'furniture-shopy.firebaseapp.com',
    storageBucket: 'furniture-shopy.appspot.com',
    measurementId: 'G-2E9VFMQSYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJTx6hwsDR-nWyXiNBDr-rTyRFwWsGqRA',
    appId: '1:597603192637:android:60de3a327da5033800bf54',
    messagingSenderId: '597603192637',
    projectId: 'furniture-shopy',
    storageBucket: 'furniture-shopy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtqIDsJBQ92pXjHBK2rHmf0V7PRD6z8o',
    appId: '1:597603192637:ios:362232a39a3ee84900bf54',
    messagingSenderId: '597603192637',
    projectId: 'furniture-shopy',
    storageBucket: 'furniture-shopy.appspot.com',
    iosClientId: '597603192637-jd815qqr8okp3cu3uldegm50hjp5j5ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureShop',
  );
}
